#!/bin/bash
#Contabilizar o número de atrasos ocorridos em cada aeroporto, listando o nome do aeroporto em uma coluna e o número de atrasos na segunda coluna (recebendo como parâmetro o ano base)
case "$1" in
  (2006)
    csv='../2006.csv'
    awk -F, '$15>0 || $16>0 {a[$17]++}END{for(i in a)print i, a[i]}' $csv | sort
    exit 1
    ;;
  (2007)
    csv='../2007.csv'
    awk -F, '$15>0 || $16>0 {a[$17]++}END{for(i in a)print i, a[i]}' $csv | sort
    exit 1
    ;;
esac
